HW8
NastyaScherbinskaya/TrainingHomeWork pull request #10
Opened 2022-03-30 19:58 UTC by NastyaScherbinskaya

Сделала подветкой 7 задания

2022-03-30 20:18 UTC, EgorAntonovich requested changes
Look for my comments

2022-03-30 20:18 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByName.cs
> +            else
this else is not necessary

2022-03-30 20:18 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByName.cs
> +            else if (x.FirstName[0] == y.FirstName[0])
you can use only if

2022-03-30 20:18 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByAssignTask.cs
> +            if (x is IAssignTask && y is IAssignTask)
I can't understand this logic =)

2022-03-30 20:18 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByNameLength.cs
> +            if ((x.FirstName.Length + x.LastName.Length) < (y.FirstName.Length + y.LastName.Length))
better use Fullname property in Employee class
`public string Fullname {get;set;} = Firstname + Lastname;`
and do smth with it.

2022-03-30 20:18 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByNameLength.cs
> +            else
this else is not necessary

2022-03-30 20:18 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByNameLength.cs
> +            else if ((x.FirstName.Length + x.LastName.Length) == (y.FirstName.Length + y.LastName.Length))
you can use only if

2022-03-30 20:18 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByTaxId.cs
> +            else return -1;
remove else

2022-03-30 20:18 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByTaxId.cs
> +            else if (x.TaxId == y.TaxId)
use only if

2022-03-30 21:50 UTC, NastyaScherbinskaya commented on TrainingHW7/TrainingHW7/Comparer/SortByAssignTask.cs
> +            if (x is IAssignTask && y is IAssignTask)
По заданию надо было отсортировать по умению ассанить таски- ITaskAssigner сначала (их допольнительно отсортировать по фамилии), потом все остальные.


обьект, который реализует интерфейс больше обьекта, который его не реализует , а если оба не реализуют, то они равны
сначала я проверяю обьекты которые реализуют интерфейс и если оба реализуют, то дополнительно по фамилии, а потом оба которые не реализуют и возвращаю 1 и 0 соответственно

2022-04-20 09:45 UTC, EgorAntonovich requested changes

2022-04-20 09:45 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByNameLength.cs
> +            {
i think you missing smth

2022-04-20 09:45 UTC, EgorAntonovich commented on TrainingHW7/TrainingHW7/Comparer/SortByTaxId.cs
> +            {
missing smth too

2022-05-16 11:00 UTC, merged